{ config, pkgs, lib, ... }:

{
  home.packages = with pkgs; [
    niri
    xwayland-satellite
    swaybg
    swayidle
    wayfreeze
    grim
    slurp
    swappy
    cliphist
    wl-clipboard
  ];

  systemd.user.services.cliphist = {
    Unit = {
      Description = "Clipboard history manager";
      PartOf = [ "graphical-session.target" ];
      After = [ "graphical-session.target" ];
    };
    Service = {
      ExecStart = "${pkgs.wl-clipboard}/bin/wl-paste --type text --watch ${pkgs.cliphist}/bin/cliphist store";
      Restart = "on-failure";
    };
    Install.WantedBy = [ "graphical-session.target" ];
  };

  systemd.user.services.cliphist-images = {
    Unit = {
      Description = "Clipboard history manager for images";
      PartOf = [ "graphical-session.target" ];
      After = [ "graphical-session.target" ];
    };
    Service = {
      ExecStart = "${pkgs.wl-clipboard}/bin/wl-paste --type image --watch ${pkgs.cliphist}/bin/cliphist store";
      Restart = "on-failure";
    };
    Install.WantedBy = [ "graphical-session.target" ];
  };

  xdg.configFile."xdg-desktop-portal/portals.conf" = {
    enable = true;
    text = ''
      [preferred]
      default=gtk
      org.freedesktop.impl.portal.ScreenCast=wlr
      org.freedesktop.impl.portal.Screenshot=wlr
    '';
  };

  xdg.configFile."niri/config.kdl" = {
    enable = true;
    text = ''
      // Niri Configuration
      // Generated by Home Manager

      input {
          keyboard {
              xkb {
                  layout "colemak_caws,rulemak_caws"                         // change it to ur own, like "en, de, fr"
                  options "caps:backspace,grp:rwin_toggle,lv3:ralt_switch"       // capslock == backspace, rSuper for layout toggle, rAlt == AltGr
              }
          }

          mouse {
              accel-speed -0.8
          }

          focus-follows-mouse               // am lamer frfr
      }


      output "DP-2" {
          mode "2560x1440@500"
          scale 1.0
      }

      layout {
          gaps 10
          center-focused-column "never"

          border {
              width 1
              active-color "#81a1c1"
              inactive-color "#4c566a"
          }

          focus-ring {
              width 1
              active-color "#81a1c1"
              inactive-color "#4c566a"
          }
      }

      window-rule {
          clip-to-geometry true
          geometry-corner-radius 12
      }

      prefer-no-csd

      binds {                                   // ColemakCAWS keybindings, bad 4 qwerty

      ///////////////////////////////
      ///   WINDOW MANIPULATIONS  ///
      ///////////////////////////////

          Mod+Return { spawn "alacritty"; }
          Mod+A { spawn "fuzzel"; }
          Mod+D { spawn "thunar"; }
          Mod+Tab { toggle-overview; }

          Mod+Q { close-window; }
          Mod+Shift+Q { close-window; }
          Mod+Shift+G { fullscreen-window; }

          Mod+R { focus-column-left; }
          Mod+T { focus-column-right; }
          Mod+F { focus-workspace-up; }
          Mod+S { focus-workspace-down; }

          Mod+Shift+R { move-column-left; }
          Mod+Shift+T { move-column-right; }
          Mod+Shift+F { move-window-up; }
          Mod+Shift+S { move-window-down; }

          Mod+1 { focus-workspace 1; }
          Mod+2 { focus-workspace 2; }
          Mod+3 { focus-workspace 3; }
          Mod+4 { focus-workspace 4; }
          Mod+5 { focus-workspace 5; }
          Mod+6 { focus-workspace 6; }
          Mod+7 { focus-workspace 7; }
          Mod+8 { focus-workspace 8; }
          Mod+9 { focus-workspace 9; }
          Mod+0 { focus-workspace 10; }

          Mod+Shift+1 { move-column-to-workspace 1; } // wane
          Mod+Shift+2 { move-column-to-workspace 2; } // tfo
          Mod+Shift+3 { move-column-to-workspace 3; } // free?
          Mod+Shift+4 { move-column-to-workspace 4; } // for
          Mod+Shift+5 { move-column-to-workspace 5; } // fih
          Mod+Shift+6 { move-column-to-workspace 6; } // sex
          Mod+Shift+7 { move-column-to-workspace 7; } // 676767
          Mod+Shift+8 { move-column-to-workspace 8; } // eih
          Mod+Shift+9 { move-column-to-workspace 9; } // hitler
          Mod+Shift+0 { move-column-to-workspace 10; } // wanenone

          Mod+Escape { focus-workspace-previous; }

          // Screenshots with frozen screen using wayfreeze
          Mod+Shift+Z { spawn "sh" "-c" "wayfreeze & FREEZE_PID=$!; sleep 0.1; grim -g \"$(slurp -d)\" - | wl-copy; kill $FREEZE_PID 2>/dev/null || true"; }
          Mod+Shift+A { spawn "sh" "-c" "wayfreeze & FREEZE_PID=$!; sleep 0.1; grim -g \"$(slurp -d)\" - | swappy -f -; kill $FREEZE_PID 2>/dev/null || true"; }

          XF86AudioRaiseVolume { spawn "wpctl" "set-volume" "@DEFAULT_AUDIO_SINK@" "5%+"; } // inf roll 4 burn out ur headphones
          XF86AudioLowerVolume { spawn "wpctl" "set-volume" "@DEFAULT_AUDIO_SINK@" "5%-"; }
          XF86AudioMute { spawn "wpctl" "set-mute" "@DEFAULT_AUDIO_SINK@" "toggle"; }      // fr i dont have kb with this bttn, but mb ive build it in the future

          // windowo management keybindings
          Mod+W { move-column-left; }
          Mod+P { move-column-right; }

          Mod+M { switch-preset-column-width; }
          Mod+Shift+V { maximize-column; }

          Mod+V { spawn "sh" "-c" "cliphist list | fuzzel --dmenu | cliphist decode | wl-copy"; }
          Mod+B { consume-window-into-column; }
          Mod+Shift+B { expel-window-from-column; }

          Mod+Space { toggle-window-floating; }



          //////////////////////////
          ///   VIDEO RECORDING  ///
          //////////////////////////

          // Run video rec buffer
          Mod+Alt+Semicolon hotkey-overlay-title="Start 3min Replay Buffer" {
              spawn "sh" "-c" "wf-recorder --buffering 180 -r 60 -c h264_vaapi -d /dev/dri/renderD128 -f ~/Videos/replay-$(date +%s).mp4"
          }

          // save video buffer
          Mod+Shift+Semicolon hotkey-overlay-title="Save Replay" {
              spawn "sh" "-c" r#"
                    pkill -INT wf-recorder
                    file=$(ls -t ~/Videos/replay-*.mp4 | head -n 1)
                    wl-copy "file://$file" -t text/uri-list
                    notify-send -t 2000 "Replay" "Saved & Restarting buffer..."

                    wf-recorder --buffering 180 -r 60 -c h264_vaapi -d /dev/dri/renderD128 -f ~/Videos/replay-$(date +%s).mp4
                "#;
          }

          // stop video buffer
          Mod+Alt+Shift+Semicolon hotkey-overlay-title="Stop & Clear Replay" {
              spawn "pkill" "-9" "wf-recorder"
          }
      }

      spawn-at-startup "sh" "-c" "systemctl --user set-environment XDG_CURRENT_DESKTOP=niri && systemctl --user import-environment WAYLAND_DISPLAY && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP"
      spawn-at-startup "swaybg" "-i" "/nix/store/4djy86fqw2i5s2wn12ns8jm0qfaprbl8-nix-d-nord-purple.jpg?raw=true" "-m" "fill"
      spawn-at-startup "xwayland-satellite"
      spawn-at-startup "waybar"
      spawn-at-startup "dunst"
      spawn-at-startup "swayidle" "-w" "timeout" "300" "niri msg action power-off-monitors"


      animations {
          window-open {
              duration-ms 200
              curve "ease-out-cubic"
          }

          window-close {
              duration-ms 150
              curve "ease-out-cubic"
          }

          workspace-switch {
              duration-ms 250
              curve "ease-out-cubic"
          }
      }

      hotkey-overlay {
          skip-at-startup
      }


    '';
  };
}
