{ config, lib, pkgs, ... }:
let
  cfg = config.sccl.forgejo;
  serverCfg = config.sccl.server;
in {
  options.sccl.forgejo = {
    enable = lib.mkEnableOption "Forgejo git forge + runner + registry";
  };

  config = lib.mkIf cfg.enable {
    # Declare secrets at host level (decrypted to /run/secrets/)
    sops.secrets."forgejo/db-password" = {
      sopsFile = ../../../secrets/db.yaml;
    };

    # NB: Forgejo's own secrets (SECRET_KEY, INTERNAL_TOKEN, oauth2 JWT, LFS JWT)
    # are generated by the module's forgejo-secrets.service into
    # /var/lib/forgejo/custom/conf/ (on the persistent /tank/forgejo bind),
    # so they survive restarts. sops values would have incompatible formats.

    # Provide an external-resolver resolv.conf for the git-ct container
    # (see bindMap resolv.conf comment).
    environment.etc."resolv.conf.git-ct".text = ''
      nameserver 1.1.1.1
      nameserver 8.8.8.8
      options edns0 trust-ad
    '';

    # Git container
    containers.git-ct = {
      autoStart = true;
      ephemeral = true;
      privateNetwork = true;
      hostAddress = "10.69.0.1";
      localAddress = "10.69.0.10";
      hostBridge = "br-svc";

      bindMounts = {
        "/var/lib/forgejo" = {
          hostPath = "/tank/forgejo";
          isReadOnly = false;
        };
        # Bind-mount host's decrypted secrets (read-only)
        "/run/secrets" = {
          hostPath = "/run/secrets";
          isReadOnly = true;
        };
        # оverride with external resolvers so push mirrors work.
        "/etc/resolv.conf" = {
          hostPath = "/etc/resolv.conf.git-ct";
          isReadOnly = true;
        };
      };

      config = { config, lib, pkgs, ... }: {
        system.stateVersion = "26.05";

        services.forgejo = {
          enable = true;
          package = pkgs.forgejo;
          stateDir = "/var/lib/forgejo";
          settings = {
            server = {
              DOMAIN = "git.${serverCfg.domain}";
              ROOT_URL = "https://git.${serverCfg.domain}/";
              HTTP_PORT = 3000;
              SSH_DOMAIN = "git.${serverCfg.domain}";
              # external port shown in clone URLs (router 194.26.100.18:22 -> host :2222 -> container)
              SSH_PORT = 22;
              DISABLE_SSH = false;
              # built-in Forgejo SSH server (git-only, no shell) binds inside the container
              START_SSH_SERVER = true;
              SSH_LISTEN_HOST = "0.0.0.0";
              # host DNATs :2222 -> 10.69.0.10:2222 (see base.nix networking.nat.forwardPorts)
              SSH_LISTEN_PORT = 2222;
            };
            service = {
              DISABLE_REGISTRATION = false;
              # public repos must be cloneable without login (REQUIRE_SIGNIN_VIEW=true made even public repos 401)
              REQUIRE_SIGNIN_VIEW = false;
            };
            migrations = {
              # allow importing repos from any external host (needed for Codeberg migration)
              ALLOWED_DOMAINS = "*";
            };
            actions = {
              ENABLED = true;
            };
            security = {
              INSTALL_LOCK = true;
            };
          };
          # Use the PostgreSQL instance on the host (reachable via the br-svc bridge IP)
          database = {
            type = "postgres";
            host = "10.69.0.1";
            port = 5432;
            name = "forgejo";
            user = "forgejo";
            passwordFile = "/run/secrets/forgejo/db-password";
            socket = null;
            createDatabase = false; # created by forgejo-db.service on the host
          };
          # Module will set server.LFS_START_SERVER and generate server.LFS_JWT_SECRET
          # into customDir/conf/ (fixes the "error saving JWT Secret" crash)
          lfs.enable = true;
        };

        networking.firewall = {
          allowedTCPPorts = [ 3000 22 2222 ];
        };
      };
    };

    # OCI registry container
    containers.registry-ct = {
      autoStart = true;
      ephemeral = true;
      privateNetwork = true;
      hostAddress = "10.69.0.1";
      localAddress = "10.69.0.17";
      hostBridge = "br-svc";

      bindMounts = {
        "/var/lib/registry" = {
          hostPath = "/tank/apps/registry";
          isReadOnly = false;
        };
      };

      config = { config, pkgs, ... }: {
        system.stateVersion = "26.05";

        services.dockerRegistry = {
          enable = true;
          listenAddress = "0.0.0.0";
          port = 5000;
          storagePath = "/var/lib/registry";
        };

        networking.firewall = {
          allowedTCPPorts = [ 5000 ];
        };
      };
    };

    # Create PostgreSQL database for Forgejo
    systemd.services.forgejo-db = {
      description = "Create Forgejo PostgreSQL database";
      after = [ "postgresql.service" ];
      wantedBy = [ "multi-user.target" ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        LoadCredential = [
          "db-password:/run/secrets/forgejo/db-password"
        ];
      };
      script = let
        psql = config.services.postgresql.package;
        asPostgres = "${pkgs.sudo}/bin/sudo -u postgres ${psql}/bin/psql";
      in ''
        DB_PASS="$(cat $CREDENTIALS_DIRECTORY/db-password)"
        ${asPostgres} -tc "SELECT 1 FROM pg_roles WHERE rolname = 'forgejo'" | ${pkgs.gnugrep}/bin/grep -q 1 || \
          ${asPostgres} -c "CREATE USER forgejo WITH PASSWORD '$DB_PASS';"
        ${asPostgres} -tc "SELECT 1 FROM pg_database WHERE datname = 'forgejo'" | ${pkgs.gnugrep}/bin/grep -q 1 || \
          ${asPostgres} -c "CREATE DATABASE forgejo OWNER forgejo;"
        ${asPostgres} -c "GRANT ALL PRIVILEGES ON DATABASE forgejo TO forgejo;"
      '';
    };
  };
}
