# Generated by nixos-generate-config at install time
# Placeholder for nixos-anywhere --generate-hardware-config
# Filesystems are provided by disko.nix - do NOT add fileSystems here
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.kernelModules = [ "kvm-amd" ];
}
