{ config, lib, pkgs, ... }:
let
  cfg = config.sccl.forgejo;
  serverCfg = config.sccl.server;
  themeNordCss = ./theme-nord-sccl.css;
in {
  options.sccl.forgejo = {
    enable = lib.mkEnableOption "Forgejo git forge + runner + registry";
  };

  config = lib.mkIf cfg.enable {
    # Declare secrets at host level (decrypted to /run/secrets/)
    sops.secrets."forgejo/db-password" = {
      sopsFile = ../../../../secrets/db.yaml;
    };

    # NB: Forgejo's own secrets (SECRET_KEY, INTERNAL_TOKEN, oauth2 JWT, LFS JWT)
    # are generated by the module's forgejo-secrets.service into
    # /var/lib/forgejo/custom/conf/ (on the persistent /tank/forgejo bind),
    # so they survive restarts. sops values would have incompatible formats.

    # Provide an external-resolver resolv.conf for the git-ct container
    # (see bindMap resolv.conf comment).
    environment.etc."resolv.conf.git-ct".text = ''
      nameserver 1.1.1.1
      nameserver 8.8.8.8
      options edns0 trust-ad
    '';

    # theme-nord-sccl.css + Cascadia Code
    # into the persistent (/tank/forgejo) volume that git-ct mounts at
    # /var/lib/forgejo/custom. Forgejo serves the custom theme from
    # custom/public/assets/css/theme-<name>.css and static assets under
    # custom/public/assets/, so theme @font-face references /assets/fonts/...
    systemd.services.forgejo-theme = {
      description = "Deploy Forgejo Nord theme + fonts";
      wantedBy = [ "multi-user.target" ];
      before = [ "container@git-ct.service" ];
      unitConfig.RequiresMountsFor = [ "/tank/forgejo" ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };
      script = ''
        install -Dm644 ${themeNordCss} /tank/forgejo/custom/public/assets/css/theme-nord-sccl.css
        for w in Regular Italic SemiBold SemiBoldItalic Bold BoldItalic; do
          install -Dm644 ${pkgs.cascadia-code}/share/fonts/truetype/CascadiaCode-$w.ttf \
            /tank/forgejo/custom/public/assets/fonts/CascadiaCode-$w.ttf
        done
      '';
    };

    # push mirrors to github/codeberg for all repos via forgesync.
    sops.secrets."github/mirror-env" = {
      sopsFile = ../../../../secrets/infra.yaml;
      mode = "0400";
    };
    sops.secrets."codeberg/mirror-env" = {
      sopsFile = ../../../../secrets/infra.yaml;
      mode = "0400";
    };

    services.forgesync = {
      enable = true;
      jobs = {
        github = {
          source = "http://10.69.0.10:3000/api/v1";
          target = "github";
          settings = {
            remirror = true;
            on-commit = true;
            mirror-interval = "0h0m0s";
          };
          secretFile = config.sops.secrets."github/mirror-env".path;
          timerConfig = {
            OnCalendar = "hourly";
            Persistent = true;
          };
        };
        codeberg = {
          source = "http://10.69.0.10:3000/api/v1";
          target = "codeberg";
          settings = {
            remirror = true;
            on-commit = true;
            mirror-interval = "0h0m0s";
          };
          secretFile = config.sops.secrets."codeberg/mirror-env".path;
          timerConfig = {
            OnCalendar = "hourly";
            Persistent = true;
          };
        };
      };
    };

    # Git container
    containers.git-ct = {
      autoStart = true;
      ephemeral = true;
      privateNetwork = true;
      hostAddress = "10.69.0.1";
      localAddress = "10.69.0.10";
      hostBridge = "br-svc";

      bindMounts = {
        "/var/lib/forgejo" = {
          hostPath = "/tank/forgejo";
          isReadOnly = false;
        };
        # Bind-mount host's decrypted secrets (read-only)
        "/run/secrets" = {
          hostPath = "/run/secrets";
          isReadOnly = true;
        };
        # оverride with external resolvers so push mirrors work.
        "/etc/resolv.conf" = {
          hostPath = "/etc/resolv.conf.git-ct";
          isReadOnly = true;
        };
      };

      config = { config, lib, pkgs, ... }: {
        system.stateVersion = "26.05";

        services.forgejo = {
          enable = true;
          package = pkgs.forgejo;
          stateDir = "/var/lib/forgejo";
          settings = {
            server = {
              DOMAIN = "git.${serverCfg.domain}";
              ROOT_URL = "https://git.${serverCfg.domain}/";
              HTTP_PORT = 3000;
              DISABLE_SSH = true;
            };
            service = {
              DISABLE_REGISTRATION = true;
              REQUIRE_SIGNIN_VIEW = false;
              LANDING_PAGE = "explore";
            };
ui = {
              # nord-sccl + built-in Forgejo themes (users can still switch per-account)
              THEMES = "forgejo-auto,forgejo-light,forgejo-dark,nord-sccl";
              DEFAULT_THEME = "nord-sccl";
            };
            actions = {
              ENABLED = true;
            };
            security = {
              INSTALL_LOCK = true;
            };
          };
          # Use the PostgreSQL instance on the host (reachable via the br-svc bridge IP)
          database = {
            type = "postgres";
            host = "10.69.0.1";
            port = 5432;
            name = "forgejo";
            user = "forgejo";
            passwordFile = "/run/secrets/forgejo/db-password";
            socket = null;
            createDatabase = false; # created by forgejo-db.service on the host
          };
          # Module will set server.LFS_START_SERVER and generate server.LFS_JWT_SECRET
          # into customDir/conf/ (fixes the "error saving JWT Secret" crash)
          lfs.enable = true;
        };

        networking.firewall = {
          allowedTCPPorts = [ 3000 ];
        };
      };
    };

    # OCI registry container
    containers.registry-ct = {
      autoStart = true;
      ephemeral = true;
      privateNetwork = true;
      hostAddress = "10.69.0.1";
      localAddress = "10.69.0.17";
      hostBridge = "br-svc";

      bindMounts = {
        "/var/lib/registry" = {
          hostPath = "/tank/apps/registry";
          isReadOnly = false;
        };
      };

      config = { config, pkgs, ... }: {
        system.stateVersion = "26.05";

        services.dockerRegistry = {
          enable = true;
          listenAddress = "0.0.0.0";
          port = 5000;
          storagePath = "/var/lib/registry";
        };

        networking.firewall = {
          allowedTCPPorts = [ 5000 ];
        };
      };
    };

    # Create PostgreSQL database for Forgejo
    systemd.services.forgejo-db = {
      description = "Create Forgejo PostgreSQL database";
      after = [ "postgresql.service" ];
      wantedBy = [ "multi-user.target" ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        LoadCredential = [
          "db-password:/run/secrets/forgejo/db-password"
        ];
      };
      script = let
        psql = config.services.postgresql.package;
        asPostgres = "${pkgs.sudo}/bin/sudo -u postgres ${psql}/bin/psql";
      in ''
        DB_PASS="$(cat $CREDENTIALS_DIRECTORY/db-password)"
        ${asPostgres} -tc "SELECT 1 FROM pg_roles WHERE rolname = 'forgejo'" | ${pkgs.gnugrep}/bin/grep -q 1 || \
          ${asPostgres} -c "CREATE USER forgejo WITH PASSWORD '$DB_PASS';"
        ${asPostgres} -tc "SELECT 1 FROM pg_database WHERE datname = 'forgejo'" | ${pkgs.gnugrep}/bin/grep -q 1 || \
          ${asPostgres} -c "CREATE DATABASE forgejo OWNER forgejo;"
        ${asPostgres} -c "GRANT ALL PRIVILEGES ON DATABASE forgejo TO forgejo;"
      '';
    };
  };
}
